// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApItzeRpqQp-HtxN5tEHdAV_tTz1A8Yis',
    appId: '1:517871709425:web:0cf48c1f3d0dc7102a4d50',
    messagingSenderId: '517871709425',
    projectId: 'altardiario-ec25f',
    authDomain: 'altardiario-ec25f.firebaseapp.com',
    storageBucket: 'altardiario-ec25f.firebasestorage.app',
    measurementId: 'G-K7330E3R2M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaMypBbxM3G-XEY7ZETaMeVUsvTRpgCwY',
    appId: '1:517871709425:android:122ed8610abff2c72a4d50',
    messagingSenderId: '517871709425',
    projectId: 'altardiario-ec25f',
    storageBucket: 'altardiario-ec25f.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApItzeRpqQp-HtxN5tEHdAV_tTz1A8Yis',
    appId: '1:517871709425:web:acd2b7c1c3d816aa2a4d50',
    messagingSenderId: '517871709425',
    projectId: 'altardiario-ec25f',
    authDomain: 'altardiario-ec25f.firebaseapp.com',
    storageBucket: 'altardiario-ec25f.firebasestorage.app',
    measurementId: 'G-W055154PD9',
  );
}
